In [24]:
import os
import pyarrow.compute as pc
from deltalake import DeltaTable
# from parameters.credentials import *

In [25]:
storage_account_name = "chemstoragednaproj001"  # "<your-storage-account>"
storage_account_key = "yeXQN4nWt83jX42gGoXTA4QVBhJnoDFHfaqD1SOk4b7n0zpK4U3yGk2waUVzH63avnW6aZwhWqli+AStEFIcvg=="  # "<your-storage-key>"  # Or use SAS token
container_name = "dna-silver-layer"
path_to_silver_table = "external/MarginMaximizer/DCS_Tags_st"

# Format the ADLS Gen2 URL
delta_table_path = f"abfss://{container_name}@{storage_account_name}.dfs.core.windows.net/{path_to_silver_table}"

In [26]:
# Set credentials via environment variables for adlfs to work with DeltaTable
os.environ["AZURE_STORAGE_ACCOUNT_NAME"] = storage_account_name
os.environ["AZURE_STORAGE_ACCOUNT_KEY"] = storage_account_key

storage_options = {"account_name": storage_account_name,
                   "account_key": storage_account_key,
                   }

In [27]:
dt = DeltaTable(delta_table_path, storage_options=storage_options)

In [31]:
table = dt.to_pyarrow_table()
sorted_indices = pc.sort_indices(table, sort_keys=[("TimeStamp", "descending")])
sorted_table = pc.take(table, sorted_indices[:])

pdf = sorted_table.to_pandas()

In [42]:
pdf[['TimeStamp', 'PI625X']]

                     TimeStamp   PI625X
0    2025-06-17 17:00:00+00:00  139.080
1    2025-06-17 16:59:00+00:00  138.770
2    2025-06-17 16:58:00+00:00  138.370
3    2025-06-17 16:57:00+00:00  138.040
4    2025-06-17 16:56:00+00:00  137.680
...                        ...      ...
1461 2025-06-16 16:05:00+00:00  121.240
1462 2025-06-16 16:04:00+00:00  121.880
1463 2025-06-16 16:03:00+00:00  122.920
1464 2025-06-16 16:02:00+00:00  123.440
1465 2025-06-16 16:01:00+00:00  123.930

[1466 rows x 2 columns]

In [43]:
pdf.columns

Index(['TimeStamp', 'H2FLOWSFC.DAYTOTAL_12', 'H2FLOWSFC.DAYTOTAL_11',
       'H2FLOWSFC.DAYTOTAL_10', 'H2FLOWSFC.DAYTOTAL_9', 'H2FLOWSFC.DAYTOTAL_8',
       'H2FLOWSFC.DAYTOTAL_7', 'H2FLOWSFC.DAYTOTAL_6', 'H2FLOWSFC.DAYTOTAL_5',
       'H2FLOWSFC.DAYTOTAL_4', 'H2FLOWSFC.DAYTOTAL_3', 'H2FLOWSFC.DAYTOTAL_2',
       'H2FLOWSFC.DAYTOTAL_1', 'HCLPRDB.CPV', 'HCLPRDA.CPV', 'HCL4_LOAD.CPV',
       'HCL3_LOAD.CPV', 'HCL2_LOAD.CPV', 'HCL1_LOAD.CPV', 'P120MW.PV',
       'P66MW.PV', 'FI615X.PV', '4H2FLOWP120.PV', '03_C_MODE_LOAD',
       '03_B_MODE_LOAD', '200FLAKER_PROD.CPV', '100FLAKER_PROD.CPV',
       '03FI8501_B.PV', '02FI8501_B.PV', '2-FI8501.PV', 'FI1353.PV',
       'FI1111_H2O2.PV', 'FIC303-H2O2', '4LI618A', 'LI618X', 'PI625X',
       'H2_FLOW_NM3', 'GF1WT1_PV', 'GF2WT1_PV', 'GF3WT1_PV', 'GF4WT1_PV',
       'HFB01AF001XQ10', 'HFB01AF003XQ10', 'HFB01AF005XQ10', 'HFB01AF007XQ10',
       'PID-22007.TOT'],
      dtype='object')

In [44]:
pdf

,TimeStamp,H2FLOWSFC.DAYTOTAL_12,H2FLOWSFC.DAYTOTAL_11,H2FLOWSFC.DAYTOTAL_10,H2FLOWSFC.DAYTOTAL_9,H2FLOWSFC.DAYTOTAL_8,H2FLOWSFC.DAYTOTAL_7,H2FLOWSFC.DAYTOTAL_6,H2FLOWSFC.DAYTOTAL_5,H2FLOWSFC.DAYTOTAL_4,...,H2_FLOW_NM3,GF1WT1_PV,GF2WT1_PV,GF3WT1_PV,GF4WT1_PV,HFB01AF001XQ10,HFB01AF003XQ10,HFB01AF005XQ10,HFB01AF007XQ10,PID-22007.TOT
0,2025-06-17 17:00:00+00:00,58614.000,17145.130,5039.250,6965.000,3323.500,98.250,11943.500,2460.000,13295.000,...,9866.060,6.966,6.859,6.865,6.863,20.763,21.890,17.324,16.923,76.865
1,2025-06-17 16:59:00+00:00,58558.000,17129.000,5039.250,6955.000,3314.500,98.250,11936.000,2454.000,13295.000,...,9917.340,6.834,6.989,6.852,6.899,20.213,21.662,17.064,16.547,75.462
2,2025-06-17 16:58:00+00:00,58502.000,17113.380,5039.250,6946.000,3306.000,98.250,11929.500,2448.500,13295.000,...,10333.210,6.902,6.892,6.878,6.921,20.126,21.953,17.137,16.561,75.739
3,2025-06-17 16:57:00+00:00,58446.000,17097.130,5039.250,6936.500,3297.000,98.250,11922.500,2443.000,13295.000,...,10372.420,6.979,6.942,6.878,6.935,19.807,21.702,16.851,16.331,74.679
4,2025-06-17 16:56:00+00:00,58390.000,17081.630,5039.250,6927.000,3288.500,98.250,11916.000,2437.000,13295.000,...,10482.710,6.748,6.863,6.798,6.915,20.033,21.325,16.413,16.030,73.883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1461,2025-06-16 16:05:00+00:00,52188.000,62.500,6288.000,5739.500,5523.500,981.250,7350.500,5983.000,14441.000,...,12839.080,None,None,None,None,None,None,None,None,None
1462,2025-06-16 16:04:00+00:00,52136.000,59.380,6286.000,5722.000,5520.500,980.250,7330.000,5976.500,14426.000,...,12771.630,None,None,None,None,None,None,None,None,None
1463,2025-06-16 16:03:00+00:00,52082.000,56.250,6283.750,5704.000,5517.500,979.250,7309.000,5970.000,14411.000,...,12523.520,None,None,None,None,None,None,None,None,None
1464,2025-06-16 16:02:00+00:00,52032.000,53.250,6281.500,5687.000,5514.500,979.250,7288.500,5963.500,14397.000,...,12879.030,None,None,None,None,None,None,None,None,None
1465,2025-06-16 16:01:00+00:00,51980.000,50.130,6279.250,5669.000,5511.000,979.250,7268.000,5957.500,14382.000,...,12621.270,None,None,None,None,None,None,None,None,None